jobs:
  send-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: إرسال رسالة تيليجرام
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="مرحبا من GitHub Actions"
