name: ุฅุฑุณุงู ุฑุณุงูุฉ ุชูููุฌุฑุงู

on:
  repository_dispatch:
    types: [send-telegram]
  workflow_dispatch:
    inputs:
      name:
        description: "ุงุณู ุงููุฑุณู"
        required: true
        default: "ุฒุงุฆุฑ"
        type: string

jobs:
  send-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: ุงูุชุญูู ูู ุงููุชุบูุฑุงุช
        run: |
          echo "ุชู ุชุดุบูู Workflow"
          echo "BOT_TOKEN ููุฌูุฏ: ${{ secrets.TELEGRAM_BOT_TOKEN != '' }}"
          echo "CHAT_ID ููุฌูุฏ: ${{ secrets.TELEGRAM_CHAT_ID != '' }}"
      
      - name: ุฅุนุฏุงุฏ ุงูุจูุงูุงุช
        id: set-data
        run: |
          # ุฅุฐุง ูุงู ููุงู ุงุณู ูุฏุฎู ุนุจุฑ workflow_dispatch
          if [ -n "${{ github.event.inputs.name }}" ]; then
            echo "NAME=${{ github.event.inputs.name }}" >> $GITHUB_ENV
          else
            # ุฅุฐุง ูุงู ููุงู ุงุณู ูู payload
            if [ -n "${{ github.event.client_payload.name }}" ]; then
              echo "NAME=${{ github.event.client_payload.name }}" >> $GITHUB_ENV
            else
              echo "NAME=ุฒุงุฆุฑ" >> $GITHUB_ENV
            fi
          fi
          
          # ุฅูุดุงุก ูุต ุงูุฑุณุงูุฉ
          MESSAGE="$NAME ูุฑุณู ุชุญูุงุชู ูู GitHub Actions ๐"
          echo "MESSAGE=$MESSAGE" >> $GITHUB_ENV
          echo "ุงูุฑุณุงูุฉ: $MESSAGE"
      
      - name: ุฅุฑุณุงู ุฑุณุงูุฉ ุชูููุฌุฑุงู
        run: |
          response=$(curl -s -w "\n%{http_code}" -X POST \
          "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="$MESSAGE")
          
          # ูุตู ุงูุงุณุชุฌุงุจุฉ ุนู ููุฏ ุงูุญุงูุฉ
          http_code=$(echo "$response" | tail -n1)
          response_body=$(echo "$response" | sed '$d')
          
          echo "ููุฏ ุงูุญุงูุฉ: $http_code"
          echo "ุฑุฏ ุงูุชูููุฌุฑุงู: $response_body"
          
          if [ "$http_code" != "200" ]; then
            echo "โ ูุดู ูู ุฅุฑุณุงู ุงูุฑุณุงูุฉ"
            exit 1
          else
            echo "โ ุชู ุฅุฑุณุงู ุงูุฑุณุงูุฉ ุจูุฌุงุญ"
          fi
