name: إرسال رسالة تيليجرام

on:
  repository_dispatch:
    types: [send-telegram]

jobs:
  send-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: التحقق من وجود المتغيرات
        run: |
          if [ -z "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]; then
            echo "❌ ERROR: TELEGRAM_BOT_TOKEN غير موجود أو فارغ"
            exit 1
          fi
          
          if [ -z "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
            echo "❌ ERROR: TELEGRAM_CHAT_ID غير موجود أو فارغ"
            exit 1
          fi
          
          echo "✅ المتغيرات موجودة وجاهزة للاستخدام"
          echo "BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}"
          echo "CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}"
      
      - name: اختبار اتصال التيليجرام
        run: |
          # اختبار البوت
          response=$(curl -s -w "\n%{http_code}" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/getMe")
          http_code=$(echo "$response" | tail -n1)
          
          if [ "$http_code" != "200" ]; then
            echo "❌ فشل اختبار البوت: رمز البوت غير صحيح"
            echo "الرد: $response"
            exit 1
          else
            echo "✅ البوت صالح ويعمل"
          fi
      
      - name: إرسال رسالة تيليجرام
        run: |
          # إرسال الرسالة
          response=$(curl -s -w "\n%{http_code}" -X POST \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="✅ تم الإرسال بنجاح من GitHub Actions - $(date)")
          
          http_code=$(echo "$response" | tail -n1)
          response_body=$(echo "$response" | sed '$d')
          
          echo "كود الحالة: $http_code"
          echo "رد التيليجرام: $response_body"
          
          if [ "$http_code" != "200" ]; then
            echo "❌ فشل في إرسال الرسالة"
            echo "تحقق من أن البوت مضاف إلى المجموعة/القناة"
            exit 1
          else
            echo "✅ تم إرسال الرسالة بنجاح"
          fi
