name: Send Telegram Message

on:
  repository_dispatch:
    types: [send_data]

jobs:
  send-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message to Telegram
        run: |
          curl -s -X POST https://api.telegram.org/bot$${{ secrets.BOT_TOKEN }}/sendMessage -d chat_id=$${{ secrets.CHAT_ID }} -d text="$${{ github.event.client_payload.message }}"
